<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Not you_ant-input css-g9hr2g</name>
   <tag></tag>
   <elementGuidId>c3fe6776-acb9-445e-9a60-f6902fbc0492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='QQwwssaa1122']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-g9hr2g</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ba56879-5c34-4ec7-8aaa-1c64cdaf8f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>c069f9fb-a9e1-464a-9ec9-24136f853dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5367652c-d451-42d6-be49-b628d8ff2083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>9284d649-068c-49b2-b17c-fde2e3b3ca05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>43433c60-188b-4404-9cb4-206fdab42c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-g9hr2g</value>
      <webElementGuid>e363bd42-c1f2-499f-a1c0-68c49162004f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>QQwwssaa1122</value>
      <webElementGuid>67c53895-1555-4e1b-9920-ad243942f458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout Layout_layout__m8Vdf css-g9hr2g&quot;]/main[@class=&quot;ant-layout-content Layout_content__-XVhO Theme_dark__XLgYe css-g9hr2g&quot;]/div[@class=&quot;ContentLayout_contentLayout__K97Ef&quot;]/div[@class=&quot;flex-column&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-g9hr2g&quot;]/div[@class=&quot;ant-form-item css-g9hr2g ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row css-g9hr2g&quot;]/div[@class=&quot;ant-col ant-col-24 ant-form-item-control css-g9hr2g&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;FloatLabel_floatLabel__+72Qy&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused ant-input-password Input_floaty__dpCYG  ant-input-affix-wrapper-status-success css-g9hr2g&quot;]/input[@class=&quot;ant-input css-g9hr2g&quot;]</value>
      <webElementGuid>3cbea7a3-2c9d-4072-ac5d-883d740121fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='QQwwssaa1122']</value>
      <webElementGuid>40b1f631-5329-4572-aecc-a0e07d24694a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div/form/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>db77307e-90b4-4db6-ab08-7a272a8c046a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>5600d21d-98bc-4152-81fb-ac83f15fcb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>d1082687-6d7b-4150-8faa-754b562de1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
