<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_ant-input css-g9hr2g Input_floa_98f4ff</name>
   <tag></tag>
   <elementGuidId>a1b80673-2d51-492b-b40b-a104c844a479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14358c9e-a4f5-4944-b755-747fb6d75d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>f81c0c69-041c-42f2-804c-9ee8e883d289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a75fa13a-1534-4299-a2bb-af8846e06495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>66cf3226-744d-4e3f-92c3-29f2139e96a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-g9hr2g Input_floaty__dpCYG </value>
      <webElementGuid>8abf1818-4f71-4292-b2c4-b1e2d5c30b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout Layout_layout__m8Vdf css-g9hr2g&quot;]/main[@class=&quot;ant-layout-content Layout_content__-XVhO Theme_dark__XLgYe css-g9hr2g&quot;]/div[@class=&quot;ContentLayout_contentLayout__K97Ef&quot;]/div[@class=&quot;flex-column&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-g9hr2g&quot;]/div[@class=&quot;ant-form-item css-g9hr2g&quot;]/div[@class=&quot;ant-row ant-form-item-row css-g9hr2g&quot;]/div[@class=&quot;ant-col ant-col-24 ant-form-item-control css-g9hr2g&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;FloatLabel_floatLabel__+72Qy&quot;]/input[@class=&quot;ant-input css-g9hr2g Input_floaty__dpCYG&quot;]</value>
      <webElementGuid>8ed502e1-d43d-49b8-a9ae-5091025fda27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>bdb03250-7318-4844-984f-0476623465b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>9b870285-6600-440f-aa60-c422ba834592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>56d1f84c-c69b-405b-9f01-5aa241a44352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>de3c76be-4b74-43f2-b32c-ea94287508d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
