<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cover Image_file-preview h-full w-full _961bca</name>
   <tag></tag>
   <elementGuidId>43298e44-0b8d-410c-9895-b0cd53257dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='live_stream-form']/div/section[2]/label[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.file-preview.h-full.w-full.absolute.top-0.left-0.bg-center.bg-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31bd0197-3156-4d23-9c37-44ff8b55e11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-preview h-full w-full absolute top-0 left-0 bg-center bg-cover</value>
      <webElementGuid>5b9efa9a-ee3e-4809-bb6e-da19afc5ca29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live_stream-form&quot;)/div[1]/section[@class=&quot;mb-4&quot;]/label[@class=&quot;border border-dashed border-white/[.25] flex justify-center items-center w-[84px] h-[150px] cursor-pointer hover:bg-white/[.05] relative&quot;]/div[@class=&quot;file-preview h-full w-full absolute top-0 left-0 bg-center bg-cover&quot;]</value>
      <webElementGuid>329fd0ed-5e5f-46eb-aa7b-c3754c9c0bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='live_stream-form']/div/section[2]/label[2]/div[2]</value>
      <webElementGuid>07d3586b-bfbe-4e23-adfb-eaacad4465ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover Image'])[1]/following::div[2]</value>
      <webElementGuid>8b1d0952-6b2a-4aab-a037-2e2586367d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::div[2]</value>
      <webElementGuid>3f2a8f5b-750b-4749-bb71-988ab185fec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::div[1]</value>
      <webElementGuid>1aeab301-2f7b-4c0d-a557-4a5e6f714786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/preceding::div[2]</value>
      <webElementGuid>97d67f7a-f855-4851-9c34-d28c46c76fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div[2]</value>
      <webElementGuid>146c78ed-04eb-4b1f-8d17-ccf0e343efb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
