<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_live_streamname</name>
   <tag></tag>
   <elementGuidId>da5a9ece-09a7-494d-bc9c-329350ad865b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stream-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stream-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0662bef3-b2ea-481a-85c0-12f12b44acd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stream-title</value>
      <webElementGuid>acafc72b-fbac-4208-a938-3b23a8313abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>06baa669-95cc-4920-b11e-81b5bd319010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>live_stream[name]</value>
      <webElementGuid>f47393e4-95af-4d22-8674-2fc1f8633fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keep it short and sweet</value>
      <webElementGuid>1571f303-a387-4586-9b2d-0108cae4b9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a584679-ffdb-4053-b267-e3592e80b32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stream-title&quot;)</value>
      <webElementGuid>eae9594e-6638-475e-8acb-8048ed5874f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stream-title']</value>
      <webElementGuid>0b428443-7f41-458d-94d5-378ca371d6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='live_stream-form']/div/section/input</value>
      <webElementGuid>1d666b2b-863d-40b0-b4c5-b8912ad84cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/input</value>
      <webElementGuid>f34a6494-7024-455c-b2f0-d82c5df3083e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'stream-title' and @name = 'live_stream[name]' and @placeholder = 'Keep it short and sweet' and @type = 'text']</value>
      <webElementGuid>cff83e4a-30cb-42e8-b352-456325252957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
