<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a breakerchong.lilocalfanatics.live</name>
   <tag></tag>
   <elementGuidId>216c944b-d49d-49b3-ae2e-7152958f203f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='live_stream-form_staffers_0_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#live_stream-form_staffers_0_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56bdb5e0-ad1f-4229-b62e-9fb4d11f8317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>live_stream-form_staffers_0_id</value>
      <webElementGuid>6fa68aec-0424-4c4e-bce3-55ca5ab259e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>live_stream[staffers][0][id]</value>
      <webElementGuid>222a01ac-8041-4cd4-b201-774874d54636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a breakerchong.li+local@fanatics.live</value>
      <webElementGuid>ad9121d9-470e-4728-a2ac-eee2fdbffa98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live_stream-form_staffers_0_id&quot;)</value>
      <webElementGuid>b0d464bd-f1fd-49cf-8f9b-2e470f729495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='live_stream-form_staffers_0_id']</value>
      <webElementGuid>4c51617d-d333-4ff9-b611-d9c7ef538257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='live_stream-form']/div/section[6]/div/select</value>
      <webElementGuid>153c1e44-9748-4575-b94f-48db1e3592bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creators'])[1]/following::select[1]</value>
      <webElementGuid>66a90d31-cced-40a0-adab-afb74469c492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[1]</value>
      <webElementGuid>57d98900-3f0d-4e98-95bc-5eb5a1e228fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add listings'])[1]/preceding::select[1]</value>
      <webElementGuid>5b0dcfc5-a74c-467c-8518-89920c982689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'live_stream-form_staffers_0_id', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>9418b2b9-28fc-497e-9dea-6165e81814c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>71d02dae-1163-45b6-a72d-033a9a7d138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'live_stream-form_staffers_0_id' and @name = 'live_stream[staffers][0][id]' and (text() = 'Select a breakerchong.li+local@fanatics.live' or . = 'Select a breakerchong.li+local@fanatics.live')]</value>
      <webElementGuid>0c25e304-01d0-4ea2-9b0a-328083f91223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
